// Vue_Frontend/src/components/Display.vue
<template>
    <div class="flex m-3 rounded-md flex-col    ">
        <div class="rounded-md p-10 bg-[#D9D9D9]">
            <marquee behavior="" direction="" class="text-[clamp(15px,4vh,200px)] ">{{defaultstr}}</marquee>
        </div>
        <div class="input flex mt-2 rounded-md">
            <input class="flex-grow rounded-md p-4 bg-[#F0F0F0] text-xl" type="text" placeholder="Enter your text here">
        </div>
    </div>
</template>

<script>
export default {
    data() {
        return {
            defaultstr: "Welcome to textboard"
        }
    },
}
</script>

<style lang="scss" scoped>

</style>

// React_TB/src/Components/Display.jsx
import { useContext, useState } from "react"
import { SharedText } from "./SharedText";
import './css/left.css'

function Display(){
  const {text,setText} = useContext(SharedText)
  const {Init} = useContext(SharedText)
  const {direction} = useContext(SharedText)
  const {direction1} = useContext(SharedText)


  function handle(){
    const Input = document.querySelector(".Input").value
    Input == "" ?  setText(Init) : setText(Input)
  }

return(
        <div class="flex m-3 rounded-md flex-col ">
            <div class="rounded-md p-10 bg-[#D9D9D9] relative" >
                <h1 className={`${direction === 1 ? "text Toright" : direction === 0? "text Toleft" : "text Stop"  } ${direction1 === 0 ? "text":"text"}`} >{text}</h1>
            </div>
            <div class="input flex mt-2 rounded-md">
                <input onChange={handle} class="Input flex-grow rounded-md p-4 bg-[#F0F0F0] text-xl" type="text" placeholder={Init}/>
            </div>
        </div>
    )
}

export default Display;
